# Generated by Django 5.0.6 on 2024-08-13 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_comment_lostitem_description_lostitem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lostitem',
            name='description',
            field=models.TextField(blank=True, default='未指定'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lostitem',
            name='image',
            field=models.ImageField(upload_to='lost_items/'),
        ),
        migrations.AlterField(
            model_name='lostitem',
            name='location',
            field=models.CharField(blank=True, default='Unknown', max_length=255),
            preserve_default=False,
        ),
    ]
