# Generated by Django 5.0.6 on 2024-09-24 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_lostitem_description_alter_lostitem_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lostitem',
            name='prefecture',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
