# Generated by Django 5.0.6 on 2024-10-04 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_lostitem_prefecture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lostitem',
            name='location',
        ),
        migrations.RemoveField(
            model_name='lostitem',
            name='status',
        ),
        migrations.AddField(
            model_name='lostitem',
            name='color',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='lostitem',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lostitem',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=35.6762, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lostitem',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=139.6503, max_digits=9),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lostitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='lost_items/'),
        ),
    ]
