# Generated by Django 4.2.16 on 2024-11-20 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_lostitem_color_lostitem_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lostitem',
            name='description',
        ),
        migrations.AddField(
            model_name='lostitem',
            name='product',
            field=models.TextField(blank=True),
        ),
    ]
