# Generated by Django 4.2.16 on 2024-11-20 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_lostitem_description_lostitem_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lostitem',
            name='product',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
