# Generated by Django 4.2.16 on 2024-12-04 05:37

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_lostitem_expire_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lostitem',
            name='expire_at',
            field=models.DateTimeField(default=app.models.default_expire_at),
        ),
    ]
